FROM docker.io/python:3.12-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends gcc && rm -rf /var/lib/apt/lists/*
COPY requirements.webui.txt .
RUN pip install --no-cache-dir -r requirements.webui.txt
COPY . .
CMD ["uvicorn", "webui.main:app", "--host", "0.0.0.0", "--port", "8080"]
